services:
  app:
    build: .
    ports:
      - target: 3000
        host_ip: 0.0.0.0  # this is the default, but for emphasis: exposed to everyone
        published: 3000
        protocol: tcp
        mode: ingress
    environment:
      DB_CONNECT: mongodb://mongo/db?readConcernLevel=majority
      OID_SECRET:
      RUST_LOG:
    read_only: true
    init: true
    depends_on:
      - mongo
    networks:
      - front-tier
      - back-tier

  mongo:
    image: mongo:5
    volumes:
      - database:/data/db
      - type: tmpfs
        target: /tmp
    read_only: true
    networks:
      - back-tier

  docs:
    build: docs
    ports:
      - target: 8080
        host_ip: 0.0.0.0
        published: 8080
        protocol: tcp
        mode: ingress
    environment:
      SWAGGER_JSON: /openapi.yaml
    init: true
    networks:
      - docs

  lint:
    profiles:
      - lint
    build:
      context: .
      target: lint
    init: true
    network_mode: none

volumes:
  database:

networks:
  front-tier:
  back-tier:
    internal: true
  docs:
