POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "username": "jay",
    "email": "test@example.com",
    "password": "qwerty"
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "username": "jay",
    "password": "qwerty"
}

###

POST http://localhost:3000/api/user/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTW9uZ29PYmplY3RJRCI6IjYyOGRkMzM5OThhMGZiZjExZGYyNjIwNyIsImlhdCI6MTY1MzY0NDI0NCwiZXhwIjoxNjg1MjAxODQ0fQ.yzGN3BAVlJGrId1Fqjgq_d4heWbyX8Uu0Y-gcQeE7CM"
}

###

DELETE http://localhost:3000/api/user/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTW9uZ29PYmplY3RJRCI6IjYyOTE5ZmIwYzg0YTFkNjc0ZGFjNzg4MyIsImlhdCI6MTY1MzcxMDg0NCwiZXhwIjoxNjg1MjY4NDQ0fQ.kqOekIpWs0CL22diLZo1Yp-0YfKRLfIUa4YNgNh4CWw"
}


###

DELETE http://localhost:3000/api/user/logoutall
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTW9uZ29PYmplY3RJRCI6IjYyOTE5ZmIwYzg0YTFkNjc0ZGFjNzg4MyIsImlhdCI6MTY1MzcxMDkyMCwiZXhwIjoxNjg1MjY4NTIwfQ.iqEjdJ52LBUGkaLct7ZijkakrpfqQacpm-dmX5b0wrE"
}

###

GET http://localhost:3000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MjkxOGY0MWY1NmExYzE5YWRkZmQ2Y2IiLCJpYXQiOjE2NTM3MDgzOTQsImV4cCI6MTY1MzcwODQwOX0.xkO29pEkzorDhdoIDv85gZ7fUYRLu0WVtYm9LD9_wJA
