// Pure communication with the backend through API routes (primarily for testing)

POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "username": "josh4",
    "email": "josh@gmail.com",
    "password": "qwerty"
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "usernameOrEmail": "1",
    "password": "qwerty"
}

###

POST http://localhost:3000/api/user/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTW9uZ29PYmplY3RJRCI6IjYyOTg2ZDBhYWQyZDI3MjI1ZjFhZGI2NSIsImlhdCI6MTY1NTI4NDM1MiwiZXhwIjoxNjg2ODQxOTUyfQ.2S6TPf453SDMduszWPfBFveSf-xg3x36GlerdvJ0wJM"
}

###

DELETE http://localhost:3000/api/user/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTW9uZ29PYmplY3RJRCI6IjYyOTE5ZmIwYzg0YTFkNjc0ZGFjNzg4MyIsImlhdCI6MTY1MzcxMDg0NCwiZXhwIjoxNjg1MjY4NDQ0fQ.kqOekIpWs0CL22diLZo1Yp-0YfKRLfIUa4YNgNh4CWw"
}


###

DELETE http://localhost:3000/api/user/logoutall
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTW9uZ29PYmplY3RJRCI6IjYyOTE5ZmIwYzg0YTFkNjc0ZGFjNzg4MyIsImlhdCI6MTY1MzcxMDkyMCwiZXhwIjoxNjg1MjY4NTIwfQ.iqEjdJ52LBUGkaLct7ZijkakrpfqQacpm-dmX5b0wrE"
}

###

GET http://localhost:3000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjk4NmQwYWFkMmQyNzIyNWYxYWRiNjUiLCJpYXQiOjE2NTUyODQzNjYsImV4cCI6MTY1NTI4NjE2Nn0.dKb86QgoXPVTGJ8iceVDbz6rTPZnj9qaCIbet0I0AGY
