// Pure communication with the backend through API routes (primarily for testing)

POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "username": "hey",
    "email": "d11didd12d00@gmail.com",
    "password": "password"
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "usernameOrEmail": "hey",
    "password": "password"
}

###

POST http://localhost:3000/api/user/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTW9uZ29PYmplY3RJRCI6IjYyYzgyODIzZjRjMDE2ZjljYjM3MTdmMSIsImlhdCI6MTY1NzI4NDY2MCwiZXhwIjoxNjg4ODQyMjYwfQ.ucgYWoST3ITkFu9dhlOrlWBAkxLrIZOiv-Hk6IuWUG8"
}

###

DELETE http://localhost:3000/api/user/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTW9uZ29PYmplY3RJRCI6IjYyYzgyODIzZjRjMDE2ZjljYjM3MTdmMSIsImlhdCI6MTY1NzI4NDY2MCwiZXhwIjoxNjg4ODQyMjYwfQ.ucgYWoST3ITkFu9dhlOrlWBAkxLrIZOiv-Hk6IuWUG8"
}


###

DELETE http://localhost:3000/api/user/logoutall
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTW9uZ29PYmplY3RJRCI6IjYyOTE5ZmIwYzg0YTFkNjc0ZGFjNzg4MyIsImlhdCI6MTY1MzcxMDkyMCwiZXhwIjoxNjg1MjY4NTIwfQ.iqEjdJ52LBUGkaLct7ZijkakrpfqQacpm-dmX5b0wrE"
}

###

GET http://localhost:3000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2Mjk4NmQwYWFkMmQyNzIyNWYxYWRiNjUiLCJpYXQiOjE2NTUyODQzNjYsImV4cCI6MTY1NTI4NjE2Nn0.dKb86QgoXPVTGJ8iceVDbz6rTPZnj9qaCIbet0I0AGY

###

POST http://localhost:3000/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmM4MGI1N2Y5ZDc0OTFjMjk3NmVkZGQiLCJpYXQiOjE2NTcyNzg2MDgsImV4cCI6MTY1NzI4MDQwOH0.4CeB6cORMe9BJLqfQ1qaWKMKtVC7BaMJzDCqOcIW1fs

{
  "genre": "RELATIONSHIPS",
  "text": "post-fix",
  "faculty": "LAW",
  "university": "UBC",
  "year": 6,
  "replying_post_ID": "62c80c29f9d7491c2976ee0a"
}

###

POST http://localhost:3000/api/posts/recents
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmM4MjgyM2Y0YzAxNmY5Y2IzNzE3ZjEiLCJpYXQiOjE2NTczNDUzNTIsImV4cCI6MTY1NzM0NzE1Mn0.x6cSEOSG2ojq8T-SJbHT9OVxGT7HPCtnkSYbGyyFw54

{
  "last_post_viewed_ID": ""
}

###

POST http://localhost:3000/api/posts/vote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmM4MjgyM2Y0YzAxNmY5Y2IzNzE3ZjEiLCJpYXQiOjE2NTczMjk4MjUsImV4cCI6MTY1NzMzMTYyNX0.k2LPaY2b74VLj227A5decKaw6On-xthiznnsDPRk-mA

{
  "post_ID": "62c80c29f9d7491c2976ee0a",
  "newVoteValue": 0
}

###

POST http://localhost:3000/api/posts/trending
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmM4MjgyM2Y0YzAxNmY5Y2IzNzE3ZjEiLCJpYXQiOjE2NTczNDYxODMsImV4cCI6MTY1NzM0Nzk4M30.GX--log3oXMBbwR9MQ7-HwPyor-4Xr5rJcLt4EofpZM


###

POST http://localhost:3000/api/search/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmM4MjgyM2Y0YzAxNmY5Y2IzNzE3ZjEiLCJpYXQiOjE2NTczMjk4MjUsImV4cCI6MTY1NzMzMTYyNX0.k2LPaY2b74VLj227A5decKaw6On-xthiznnsDPRk-mA

{
  "username": "matt"
}

###

POST http://localhost:3000/api/search/universities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MmFmZjliMDhhZDA3N2YyMTdjNzEzMDUiLCJpYXQiOjE2NTY3MzE1MzcsImV4cCI6MTY1NjczMzMzN30.VTrs0Xq4Aej386Tg30K8rditJz-3IEXWgJr71EUV4RM

{
  "university": "victorr"
}
